### ISSUE TITLE
some sample *apks

### ISSUE THREAD

**Issue by Raphi-2Code** [PaologGithub/UrsinaForMobile#4]
Hi @PaologGithub,
u could add some sample apk files, just for demonstration

**Comment by PaologGithub** [comment]
I will do it, but later

**Comment by Raphi-2Code** [comment]
k

**Comment by Raphi-2Code** [comment]
it's really a new era of ursina

**Comment by PaologGithub** [comment]
yeah

**Comment by Raphi-2Code** [comment]
i feel happy building my first ursina android game ...

**Comment by PaologGithub** [comment]
:,)

**Comment by Raphi-2Code** [comment]
wait, u could turn the ursina lvl editor to an android application, this would be super cool xD

**Comment by PaologGithub** [comment]
I will watch what can I do about it, it will be difficult

**Comment by Raphi-2Code** [comment]
kk
