### ISSUE TITLE
v0.0.0

### ISSUE THREAD

**Issue by Raphi-2Code** [PaologGithub/UrsinaForMobile#7]
### Discussed in https://github.com/PaologGithub/UrsinaForMobile/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **PaologGithub** November 26, 2024</sup>
First release to fully support ursina, so you can port your game on it

<hr /><em>This discussion was created from the release <a href='https://github.com/PaologGithub/UrsinaForMobile/releases/tag/0.0.0'>v0.0.0</a>.</em></div>

**Comment by Raphi-2Code** [comment]
Yipee!!! 🎉🥳🚀

**Comment by Raphi-2Code** [comment]
![image](https://github.com/user-attachments/assets/b9ee9557-4b0d-4904-916b-3c8e22573f7c)
This is so cool!!

**Comment by PaologGithub** [comment]
So I need to do more work to make ursina on iOS ...

**Comment by Raphi-2Code** [comment]
it basically means that xD

**Comment by PaologGithub** [comment]
:,(

**Comment by Raphi-2Code** [comment]
![image](https://github.com/user-attachments/assets/68472433-9bf9-4e52-913c-97ccdf74806e)

**Comment by PaologGithub** [comment]
:,((((

**Comment by PaologGithub** [comment]
# stop

**Comment by Raphi-2Code** [comment]
![image](https://github.com/user-attachments/assets/8bde4ddb-b3db-4356-9280-32cc9c58f796)

**Comment by Raphi-2Code** [comment]
ima stop
